# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Table.destroy_all

Table.create(floor: 0, num: 1, descrip: "Basement table by the heater")
Table.create(floor: 0, num: 2, descrip: "Basement table by Jon and Dave's room")
Table.create(floor: 1, num: 3, descrip: "Table next to where Susan barfed")
Table.create(floor: 1, num: 4, descrip: "Backyard table")
Table.create(floor: 2, num: 5, descrip: "In the attic next to the potato gun")

Team.destroy_all

Team.create(name: "Designated Drinkers")
Team.create(name: "Beer View Mirrors")
Team.create(name: "Bad News Beers")
Team.create(name: "Beer Pressure")
Team.create(name: "2 guys 10 cups")
Team.create(name: "King Pong")
Team.create(name: "40 oz All Stars")
Team.create(name: "Alcoholics Unanimous")
Team.create(name: "2/3 of a Threesome")
Team.create(name: "Balls of Fame")
Team.create(name: "Beer Dumpsters")
Team.create(name: "Better Late than Pregnant")
Team.create(name: "Blood, Sweat, and Beers")
Team.create(name: "Brain Cell Butchers")
Team.create(name: "By the Beard of Zeus")
Team.create(name: "Cheech and Pong")
Team.create(name: "Chicks with Balls")
Team.create(name: "Death by Chuck Norris")
Team.create(name: "Dirty Ball Water")
Team.create(name: "Double Dunk")
Team.create(name: "Ert and Bernie")
Team.create(name: "Fifth Year Seniors")
Team.create(name: "Five Dollar Footlongs")
Team.create(name: "Former Teen Idols")
Team.create(name: "Game of Throws")
Team.create(name: "If the Table Was a Cup")
Team.create(name: "It's ON like Donkey Kong")
Team.create(name: "Keep Getting Distracted")
Team.create(name: "Kim Jong Un-believable")
Team.create(name: "Knuckle Draggers")
Team.create(name: "The Liver Is Evil ... It Must Be Punished")
Team.create(name: "Lunachicks")
Team.create(name: "Menace to Sobriety")
Team.create(name: "More Cowbell")
Team.create(name: "Mustaches and Mullets")
Team.create(name: "Nice Reracks")
Team.create(name: "No Drinks Left Behind")
Team.create(name: "Often Imitated Never Duplicated")
Team.create(name: "One Down Nine to Go")
Team.create(name: "Plastered Bastards")
Team.create(name: "Pong for the Cure")
Team.create(name: "Pong with Benefits")
Team.create(name: "Release the Kraken")
